### ISSUE TITLE
dont Working

### ISSUE THREAD

**Issue by UrielRicardo** [nikhildand/d3adsh0t#1]
I think it acttualy dont working, can u confirm?

**Comment by nikhildand** [comment]
Hey, I haven't uploaded the weights file (which is used to process detections), you should prepare your own data set and train it, and upload your weights file to process detections and then the orders are deployed.

I mentioned I won't be uploading the weights file, because people could abuse it in online matchmaking and I am not a fan of cheating in online games, Sorry for that !!

Apart from that if you have any issues after training your own weights for the yolov5s, I can help you.

**Comment by UrielRicardo** [comment]
yeah, no problem actually i'm more interested in antirecoil because i'm registering the pattern of the gun but it isn't working, can you help me?

**Comment by nikhildand** [comment]
You have to press F7 to switch on the toggle for Recording the pattern, after you do so, click on the pattern for the first 10 bullets and then you have to click once more, and then the relative mouse movement from bullet to bullet will be displayed on the cmd, isn't it showing for you ?, if it has showed you you have to manually copy paste it onto a notepad and load it through VisualizeData.py to get statistical inference.

If you are taking about the Auto-Recoil Control, then in the AntiRecoil.py you have to change how mouse movements are deployed, because many games patch mouse movements, you could possibly try using interception for that.

**Comment by VenoSnake** [comment]
Have you got it to work ?!

**Comment by UrielRicardo** [comment]
Unfortunately no, I believe I'm doing something wrong, do you have a
tutorial for me?

Em seg., 28 de set. de 2020 às 15:28, Nikhil Dandamudi <
notifications@github.com> escreveu:

**Comment by VenoSnake** [comment]
ill record you a video and send to you in a day or two (I am working on a other project now) .

**Comment by UrielRicardo** [comment]
thank so much man.

Em ter., 29 de set. de 2020 às 06:20, Nikhil Dandamudi <
notifications@github.com> escreveu:

**Comment by UrielRicardo** [comment]
got it?
you can send it to my email winchesteruriel@gmail.com
